name: "Deploy to Server"

on:
    workflow_dispatch:
    # push:
    #     branches: 
    #         - main
jobs: 
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Tailscale
              uses: tailscale/github-action@v1
              with:
                authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

            - name: SSH to Server
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: morgan
                username: cog25
                password: ${{ secrets.PASSWORD }}
                key: ${{ secrets.KEY }}
                port: 22
                script: |-
                    cd ${{secrets.DIR}}
                    git pull
                    docker compose exec minecraft rcon-cli me [Server will automatically restart in 30s]
                    sleep 30
                    docker compose up -d
                    exit
                
                    