name: "Deploy to Server"

on:
    workflow_dispatch:
    workflow_call:
    push:
        branches: 
            - main
jobs: 
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - name: Setup Tailscale
              uses: tailscale/github-action@v1
              with:
                authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

            - name: Setup SSH Key
              run: |-
                mkdir ~/.ssh
                echo "${{ secrets.KEY }}" > ~/.ssh/id_ed25519
            
            - name: Connect to Server
              shell: bash
              run: |-
                cd .github/workflows
                { echo -n 'mv ${{ secrets.DIR }}'; cat deploy.sh; } > deploy.sh
                cat deploy.sh | ssh morgan
