name: "Deploy to Server"

on:
    workflow_dispatch:
    workflow_call:
    push:
        branches: 
            - main
jobs: 
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Tailscale
              uses: tailscale/github-action@v1
              with:
                authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

            - name: Setup SSH
                shell: bash
                run: 
                